
name = "heygen-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "726158b3f2032e7180f4ad96922fb820"

[vars]
# The HeyGen API key will be passed from the frontend through the X-Api-Key header

# The worker will be available at heygen-proxy.tobymather.workers.dev
workers_dev = true

# Configure CORS
[vars.CORS]
allowed_origins = ["*"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["Content-Type", "X-Api-Key", "Authorization"]
