name = "heygen-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "726158b3f2032e7180f4ad96922fb820"
workers_dev = true

[vars]
LOG_LEVEL = "debug" 

[observability]
enabled = true
head_sampling_rate = 1